#!/usr/bin/python


def tree_to_S3(sql_tree):
    '''

    keyword args:
        sql_tree: SQL tree, as generated by sql_to_tree module



    returns:

    '''


if __name__ == '__main__':

    import sql_to_tree

    input_sql = """select c.customer_name, o.order_date, sum(o.orders)
                from tcph.customer as c, tcph.order o, tcph.part
                where c.customer_id = o.customer_id
                and o.part_number = tcph.part.part_number
                and c.customer_id = 1
                group by c.customer_name, o.order_date
                order by c.customer_name;"""

    print(tree_to_postgres_sql(sql_to_tree.sql_to_tree(input_sql),'Oracle'))
